feat: Add --pretty option to CLI tool
eemeli/yaml pull request #559
Opened 2024-06-30 13:43 UTC by danielbayley

Add a `--pretty` option, to be used with `--json` output.

2024-07-01 06:48 UTC, eemeli requested changes
I have two concerns with this change:

1. Could you clarify what's the use case of pretty-printed JSON output? For single-shot manual use, wouldn't the same be served by piping the output to a separate JSON prettifier like `jq`?

2. Naming the option as "pretty" and only affecting the JSON output seems rather misleading. Either the option needs to make sense independently of `--json`, or it needs to be named more specifically.

2024-07-01 11:34 UTC, eemeli commented
> > 1. Could you clarify what's the use case of pretty-printed JSON output? For single-shot manual use, wouldn't the same be served by piping the output to a separate JSON prettifier like `jq`?
> 
> _Non_ single-shot manual use… Like in `package.json` ([`package.yaml`](https://github.com/pnpm/pnpm/issues/1100)) `scripts`.

Eh, not sure that it really makes sense to prettify output that's meant for machine consumption, as it risks creating JSON files that will be presumed to be the source of truth, rather than intermediate build assets. But I'll grant you that there's probably a valid use case somewhere here.

> > 2. Naming the option as "pretty" and only affecting the JSON output seems rather misleading. Either the option needs to make sense independently of `--json`, or it needs to be named more specifically.
> 
> I had a similar thought, but there is no such thing as `--pretty` YAML, it already has to be indented…
> 
> I think the ideal API would be an optional parameter, maybe to `--json`, e.g `--json 2` or something, but that isn’t really a feature of `util.parseArgs`. How about `--indent`? What other name do you think would be better?

`--indent` works, esp. as it's already an [option](https://eemeli.org/yaml/#tostring-options) for YAML formatting. Switch this PR to that and make it apply to YAML output as well?

2024-07-01 11:56 UTC, danielbayley commented
> it risks creating JSON files that will be presumed to be the source of truth

Well the YAML files are the source… But a _lot_ of tools only work from JSON. Harder to debug if it _has_ to be minified also…

> `--indent` works, esp. as it's already an [option](https://eemeli.org/yaml/#tostring-options) for YAML formatting. Switch this PR to that and make it apply to YAML output as well?

Good idea, will look into it…

2024-07-01 13:36 UTC, eemeli requested changes
Overall the API looks good, see inline for implementation changes.

2024-07-01 13:36 UTC, eemeli commented on src/cli.ts
> +        indent: { type: 'string', short: 'i' }
Should keep these in alphabetic order.

2024-07-01 13:36 UTC, eemeli commented on src/cli.ts
> +  --pretty, -p  Output pretty-printed JSON.
Needs an update.

2024-07-01 13:36 UTC, eemeli commented on src/cli.ts
> +          console.log(JSON.stringify(opt.single ? data[0] : data, null, Number(opt.indent)))
Note also the other places where output is being generated: lines 97, 115, and 164 will need to be updated. It'd probably be best to determine a single `jsonIndent` value somewhere above, and use that for the `JSON.stringify()` calls, and handle the yaml Document's `toString{ indent })` value separately.

2024-07-01 13:36 UTC, eemeli commented on tests/cli.ts
The lexer, CST, and YAML document outputs will also need `--indent` tests.

2024-07-01 19:50 UTC, danielbayley commented on tests/cli.ts
All passing, except something weird going on with the CST unit test… Whether I hard code it as a string, or do `JSON.stringify` also in the test. Any ideas?

2024-07-07 08:42 UTC, eemeli commented on tests/cli.ts
> +        'hello: world',
The expected output includes a trailing newline, which is missing from here.

```suggestion
        'hello: world\n',
```

2024-07-07 08:45 UTC, eemeli approved these changes
Thank you, this looks good! Sorry for the delay in getting to this. There was a missing newline from the test source, which I added to get the test to pass.

2024-07-07 08:45 UTC, merged

2024-07-07 16:05 UTC, danielbayley commented
> Thank you, this looks good! Sorry for the delay in getting to this. There was a missing newline from the test source, which I added to get the test to pass.

No worries, life gets in the way… I know! Ah cool, was that at the end?